name: Build Whot APK
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable
          command: buildozer android debug

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Whot-Mobile-APK
          path: ${{ steps.buildozer.outputs.filename }}
